///#GLOBALS Lib Sys
/* LIB_DEFINITION{
  "name": "Lib_Expense_Transaction_Parser_GL1025_Mapping_V12.0.461.0",
  "libraryType": "LIB",
  "scriptType": "SERVER",
  "comment": "Mapping for the GL1025 name of field in specs to name in form",
  "require": []
}*/
var Lib;
(function (Lib) {
    var Expense;
    (function (Expense) {
        var Transaction;
        (function (Transaction) {
            var Parser;
            (function (Parser) {
                var GL1025;
                (function (GL1025) {
                    var _mapping = {
                        headerMapping: {
                            "Record Type": null,
                            "Reporting Group": null,
                            "Recipient Number": null,
                            "Report Prefix": null,
                            "Report Number": null,
                            "Client Data File Version": null,
                            "File Frequency Delivery Indicator ": null,
                            "Data File Create Date": null,
                            "Data File Julian Date": null,
                            "File (Layout) Version Number": null,
                            "File Version Date": null,
                            "File Type Indicator": null,
                            "Total Record Count": null,
                            "Neutral ISO Currency Code": null,
                            "Neutral Currency - Decimal Place Indicator": null,
                            "Total Daily Unbilled Amount - Neutral Currency": null,
                            "Total Card Member Balance - Neutral Currency": null,
                            "Data File Create Run Time": null,
                            "Total Transaction Count": null
                        },
                        marketTable: null,
                        marketMapping: {
                            "Record Type": null,
                            "Data File Content Date": null,
                            "Data File Content Date - Julian": null,
                            "No Data Content Indicator": null,
                            "Record Count": null,
                            "Market Code": null,
                            "ISO Currency Code - Primary Currency": null,
                            "Decimal Place Indicator - Primary Currency": null,
                            "ISO Currency Code - Secondary Currency": null,
                            "Decimal Place Indicator - Secondary Currency": null,
                            "ISO Currency Code - Neutral Currency": null,
                            "Decimal Place Indicator - Neutral Currency": null,
                            "Total Daily Unbilled Amount - Primary Currency": null,
                            "Total Daily Unbilled Amount - Secondary Currency": null,
                            "Total Daily Unbilled Amount - Neutral Currency": null,
                            "Total Card Member Balance - Primary Currency": null,
                            "Total Card Member Balance - Secondary Currency": null,
                            "Total Card Member Balance - Neutral Currency": null,
                            "Total Market Transaction Count": null
                        },
                        transactionTable: "LineTransaction__",
                        transactionMapping: {
                            "Record Type": null,
                            "Market Code": null,
                            "Global Client Origin Identifier": null,
                            "Requesting Control Account Number": null,
                            "Requesting Control Account Name": null,
                            "Billing Basic Control Account Number": null,
                            "Billing Basic Control Account Name": null,
                            "Account Type": null,
                            "Originating Basic Control Account Number": null,
                            "Originating Card Member Account Number": null,
                            "Liability Code": null,
                            "Billing Account Number": null,
                            "Last Name": null,
                            "First Name": null,
                            "Middle Name": null,
                            "Card Member Embossed Name": "CardholderName__",
                            "Employee Id": "EmployeeID__",
                            "Basic Control Account Company Doing Business As Name": null,
                            "Basic Control Account Company Legal Name": null,
                            "Requesting Control Account Company DBA Name": null,
                            "Requesting Control Account Company Legal Name": null,
                            "Cost Center": null,
                            "Universal Number": null,
                            "Language Preference Code": null,
                            "Business Process Date": null,
                            "Charge Date": "TransactionDate__",
                            "Data File Date": null,
                            "Data File Julian Date": null,
                            "Bill Date": null,
                            "Transaction ID": "TransactionID__",
                            "Card Member Reference Number": null,
                            "Record Of Charge ID": null,
                            "Billed Amount": "BilledAmount__",
                            "Billed Tax Amount": null,
                            "Billed Decimal Place Indicator": null,
                            "Billed Currency ISO Code": "ISOBilledCurrencyCode__",
                            "Euro - Billed Amount": null,
                            "Euro - Billed Tax Amount": null,
                            "Euro - Billed Decimal Place Indicator": null,
                            "Euro - Billed Currency ISO Code": null,
                            "Local Charge Amount": "LocalAmount__",
                            "Local Tax Amount ": null,
                            "Local Decimal Place Indicator": null,
                            "Currency Exchange Rate": "CurrencyExchangeRate__",
                            "Local Currency ISO Code": "ISOLocalCurrencyCode__",
                            "Local Country ISO Code": null,
                            "Neutral Currency Billed Amount": null,
                            "Neutral Currency Decimal Place Indicator": null,
                            "Neutral ISO Currency Code": null,
                            "Transaction Type Code": null,
                            "Financial Category Code": null,
                            "MIS Industry Code": null,
                            "Genesis Major Industry Code": null,
                            "SIC Code": null,
                            "SIC Division Code": null,
                            "Genesis Detail Industry Code": null,
                            "Transaction Fee Indicator": null,
                            "Charge Description Line 1": "ExpenseDescription__",
                            "Charge Description Line 2 ": null,
                            "Charge Description Line 3": null,
                            "Charge Description Line 4": null,
                            "Charge Description Line 5": null,
                            "Redefines": null,
                            "Airline Redefine": null,
                            "Air Departure Date": null,
                            "Air Routing": null,
                            "Air Class of Service": null,
                            "Air Carrier Code": null,
                            "Travel Agency Air Ticket Issuer": null,
                            "Travel Agency Air Issuer City": null,
                            "Travel Agency Air Issuer Region": null,
                            "Travel Agency Air Issuer Country Code (ISO)": null,
                            "Air Passenger Name": null,
                            "Travel Agency Identifier": null,
                            "Air Ticket Number": null,
                            "Flight Number": null,
                            "Mileage": null,
                            "Domestic or International Code": null,
                            "Predominant Carrier Code": null,
                            "Predominant Class Category Code": null,
                            "Predominant Supplier Class Code": null,
                            "Round-trip Indicator": null,
                            "Hotel Redefine": null,
                            "Hotel Description of Charge": null,
                            "Hotel Guest Name": null,
                            "Hotel Arrival Date": null,
                            "Hotel Depart Date": null,
                            "Hotel Stay Duration": null,
                            "Hotel Room Rate": null,
                            "Hotel City": null,
                            "Hotel State Code": null,
                            "Hotel State (Latin America/Caribbean Region)": null,
                            "Hotel Region ID": null,
                            "Hotel Country ID (ISO)": null,
                            "Hotel Phone Number": null,
                            "Hotel Folio Number": null,
                            "Car Rental Redefine": null,
                            "Car Rental Date": null,
                            "Car Return Date": null,
                            "Car Rental City": null,
                            "Car Rental State Code": null,
                            "Car Rental State (Latin America/Caribbean Region)": null,
                            "Car Rental Region ID": null,
                            "Car Rental Country ID (ISO)": null,
                            "Car Return City": null,
                            "Car Return State Code": null,
                            "Car Return State  (Latin America/Caribbean Region)": null,
                            "Car Return Region ID": null,
                            "Car Return Country ID (ISO)": null,
                            "Car Renter Name": null,
                            "Car Rental Days": null,
                            "Car Rental Agreement Number": null,
                            "Car Rental Days 2": null,
                            "End of Redefines": null,
                            "ISO Merchant Category Code": "MerchantCategory__",
                            "DDA Number (Demand Deposit Account )": null,
                            "Banking Routing Number": null,
                            "Funds Access Log Date": null,
                            "Funds Access Log Time": null,
                            "Machine Number": null,
                            "Terminal Location": null,
                            "Cash Batch Number ": null,
                            "Supplier Reference Number": null,
                            "Service Establishment (SE) Number": null,
                            "Service Establishment Chain Name": null,
                            "Service Establishment Brand Name": null,
                            "Service Establishment ABN Number / Tax Company ID": null,
                            "Service Establishment  Name 1": "MerchantName__",
                            "Service Establishment Name 2": null,
                            "Service Establishment Address Line 1": null,
                            "Service Establishment Address Line 2": null,
                            "Service Establishment Address Line 3": null,
                            "Service Establishment Address Line 4": null,
                            "Service Establishment City Name": null,
                            "Service Establishment Region Code": null,
                            "Service Establishment State/Province Code": null,
                            "Service Establishment Postal Code": null,
                            "Service Establishment Country Name": null,
                            "Service Establishment Country Code": null,
                            "Service Establishment Corporate Status Code": null,
                            "Service Establishment Purchase Card Code": null,
                            "Service Establishment Sales Tax Collected Flag ('Y' or 'N')": null,
                            "Client Registered Business Number": null,
                            "Client  Registered Business Name": null,
                            "Amex Registered Business Number": null,
                            "Capture Center Code": null,
                            "Corporation ID": null,
                            "Tax Evaluation Date": null,
                            "Goods and Services Tax": null,
                            "Service Establishment Supply Tax Class": null,
                            "Bill Cycle Code": null
                        },
                        cardTable: null,
                        cardMapping: {
                            "Record Type ": null,
                            "Basic Control Account Number": null,
                            "Basic Control Account Name": null,
                            "Card Member Account Number": null,
                            "Last Name": null,
                            "First Name": null,
                            "Middle Name": null,
                            "Card Member Embossed Name": null,
                            "Account Type": null,
                            "Card Member Status Code": null,
                            "Orignal Card Member Number": null,
                            "Cancel Code": null,
                            "Liability Code": null,
                            "Corporation ID": null,
                            "Primary ISO Currency Code": null,
                            "Decimal Place Indicator - Primary Currency": null,
                            "Secondary ISO Currency Code": null,
                            "Decimal Place Indicator - Secondary Currency": null,
                            "Neutral ISO Currency Code": null,
                            "Decimal Place Indicator - Neutral Currency": null,
                            "Debit Record Balance - Primary Currency": null,
                            "Debit Record Balance - Secondary Currency": null,
                            "Debit Record Balance - Neutral Currency": null,
                            "Card Member Debit Record Count": null,
                            "Credit Record Balance - Primary Currency": null,
                            "Credit Record Balance - Secondary Currency": null,
                            "Credit Record Balance - Neutral Currency": null,
                            "Card Member Credit Record Count ": null,
                            "Card Member Balance - Primary Currency": null,
                            "Card Member Balance - Secondary Currency": null,
                            "Card Member Balance - Neutral Currency": null,
                            "Card Member Total Record Count": null,
                            "GST Amount Total": null,
                            "GST Amount Total - Neutral Currency": null,
                            "Previous Card Member Balance - Primary Currency": null,
                            "Previous Card Member Balance - Secondary Currency": null,
                            "Previous Card Member Balance - Neutral Currency": null,
                            "Accumulated Card Member Debits - Primary Currency": null,
                            "Accumulated Card Member Debits - Secondary Currency": null,
                            "Accumulated Card Member Debits - Neutral Currency": null,
                            "Accumulated Debit Record Count": null,
                            "Accumulated Card Member Credits - Primary Currency": null,
                            "Accumulated Card Member Credits - Secondary Currency": null,
                            "Accumulated Card Member Credits - Neutral Currency": null,
                            "Accumulated Credit Record Count": null,
                            "Dollar Balance Conversion Rate": null,
                            "Dollar Balance Conversion Rate - Decimal Place Indicator": null,
                            "Dollar Balance Conversion Amount": null,
                            "Dollar Balance Conversion Amount - Decimal Place Indicator": null,
                            "Bill Cycle Code": null
                        },
                        trailerMapping: {
                            "Record Type": null,
                            "Reporting Group": null,
                            "Recipient Number": null,
                            "Report Prefix": null,
                            "Report Number": null,
                            "Client Data File Version": null,
                            "File Frequency Delivery Indicator ": null,
                            "Data File Create Date": null,
                            "Data File Julian Date": null,
                            "File (Layout) Version Number": null,
                            "File Version Date": null,
                            "File Type Indicator": null,
                            "Total Record Count": null,
                            "Neutral ISO Currency Code": null,
                            "Neutral Currency - Decimal Place Indicator": null,
                            "Total Daily Unbilled Amount - Neutral Currency": null,
                            "Total Card Member Balance - Neutral Currency": null,
                            "Data File Create Run Time": null,
                            "Total Transaction Count": null
                        }
                    };
                    function getMapping() {
                        return _mapping;
                    }
                    GL1025.getMapping = getMapping;
                })(GL1025 = Parser.GL1025 || (Parser.GL1025 = {}));
            })(Parser = Transaction.Parser || (Transaction.Parser = {}));
        })(Transaction = Expense.Transaction || (Expense.Transaction = {}));
    })(Expense = Lib.Expense || (Lib.Expense = {}));
})(Lib || (Lib = {}));
